import { productAssets } from './assets';

export type Category = 'tent' | 'shoe';

export type Product = {
  id: string;
  category: Category;
  title: string;
  subtitle: string;
  price: number;
  oldPrice?: number;
  discount?: string;
  installments: string;
  image: string;
  gallery: string[];
  rating: number;
  reviews: number;
  shipping: string;
  full?: boolean;
  promoted?: boolean;
  available: number;
  seller: string;
  color?: string;
  sizes?: string[];
  target: string;
  details: string[];
  attributes: Array<[string, string]>;
};

export const categories = [
  'Archive',
  'Outdoor',
  'Apparel',
  'Footwear',
  'Everyday Gear',
  'Home',
  'Tools',
  'Technology',
  'Travel',
  'Wellness',
  'Books and Media',
];

export const shoeSizes = ['US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'];

const tentGallery = productAssets.tents.gallery;
const shoeGallery = productAssets.shoes.gallery;
const generatedTentHero = '/demo-assets/generated/tent-hero-web.png';
const generatedShoeHero = productAssets.shoes.cards[0];

export const PRODUCT_PRICE_MULTIPLIER = 3;

const baseProducts: Product[] = [
  {
    id: 'tent-primary',
    category: 'tent',
    title: 'Portable Camping Tent House for 3-4 People, Beige',
    subtitle: 'Best match for a short hiking trip',
    price: 139.95,
    oldPrice: 199.95,
    discount: '30% OFF',
    installments: '4 payments of $34.99',
    image: generatedTentHero,
    gallery: [generatedTentHero, ...tentGallery],
    rating: 4.8,
    reviews: 214,
    shipping: 'Free shipping tomorrow',
    full: true,
    promoted: false,
    available: 17,
    seller: 'Lawuto Outdoor',
    color: 'Beige',
    target: 'product-tent-primary',
    details: [
      'Sleeps 3 to 4 people with a tall center profile.',
      'Includes carry bag, rain cover, stakes, and guy lines.',
      'Water-resistant fabric for weekend camping conditions.',
      'Quick assembly frame for fast setup at the campsite.',
    ],
    attributes: [
      ['Capacity', '3 to 4 people'],
      ['Weight', '3.2 kg'],
      ['Recommended use', 'Camping and hiking'],
      ['Condition', 'New'],
    ],
  },
  {
    id: 'tent-auto',
    category: 'tent',
    title: 'Automatic Quick Open Large Camping Tent for 3 to 4',
    subtitle: 'Fast setup tent',
    price: 119,
    oldPrice: 169,
    discount: '30% OFF',
    installments: '4 payments of $29.75',
    image: productAssets.tents.cards[0],
    gallery: [productAssets.tents.cards[0], ...tentGallery.slice(1, 5)],
    rating: 4.6,
    reviews: 88,
    shipping: 'Free international shipping',
    full: false,
    promoted: true,
    available: 8,
    seller: 'Outdoor Direct',
    color: 'Green',
    target: 'product-tent-automatic',
    details: ['Automatic open frame.', 'Mesh windows for airflow.', 'Compact storage bag included.'],
    attributes: [['Capacity', '3 to 4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-three',
    category: 'tent',
    title: 'Dark Green 3-Person Camping Tent, Easy Install',
    subtitle: 'Compact tent for trails',
    price: 79,
    oldPrice: 109,
    discount: '28% OFF',
    installments: '4 payments of $19.75',
    image: productAssets.tents.cards[3],
    gallery: [productAssets.tents.cards[3], ...tentGallery.slice(2, 6)],
    rating: 4.5,
    reviews: 143,
    shipping: 'Free shipping',
    full: true,
    available: 26,
    seller: 'Camp Store',
    color: 'Dark green',
    target: 'product-tent-green',
    details: ['Easy-pitch pole system.', 'Good ventilation for warm weather.', 'Water-resistant floor.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-pop',
    category: 'tent',
    title: 'Pop Up Waterproof Tent with 2 Entrances for Camping',
    subtitle: 'Roomy pop-up option',
    price: 149,
    oldPrice: 199,
    discount: '25% OFF',
    installments: '4 payments of $37.25',
    image: productAssets.tents.cards[9],
    gallery: [productAssets.tents.cards[9], ...tentGallery.slice(0, 4)],
    rating: 4.7,
    reviews: 67,
    shipping: 'Free shipping',
    available: 10,
    seller: 'Travel Kit',
    color: 'Blue',
    target: 'product-tent-popup',
    details: ['Pop-up structure.', 'Two doors.', 'Built for casual weekend camping.'],
    attributes: [['Capacity', '2 to 3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-beach',
    category: 'tent',
    title: 'Compact Rainfly Tent for 2 or 3 People',
    subtitle: 'Lightweight trail tent option',
    price: 49,
    oldPrice: 69,
    discount: '29% OFF',
    installments: '2 payments of $24.50',
    image: productAssets.tents.cards[6],
    gallery: [productAssets.tents.cards[6], ...tentGallery.slice(3, 7)],
    rating: 4.4,
    reviews: 52,
    shipping: 'Free shipping',
    available: 32,
    seller: 'North Route',
    color: 'Glacier gray',
    target: 'product-tent-shade',
    details: ['Enclosed tent body with rainfly.', 'Front door with mesh ventilation.', 'Packs small for weekend trails.'],
    attributes: [['Capacity', '2 to 3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-four-auto',
    category: 'tent',
    title: 'Automatic Camping Tent for 4 People with Carry Bag',
    subtitle: 'Automatic setup family tent',
    price: 169,
    oldPrice: 229,
    discount: '26% OFF',
    installments: '4 payments of $42.25',
    image: productAssets.tents.cards[4],
    gallery: [productAssets.tents.cards[4], ...tentGallery.slice(0, 5)],
    rating: 4.6,
    reviews: 116,
    shipping: 'Free shipping',
    full: true,
    available: 19,
    seller: 'Camping Direct',
    color: 'Blue',
    target: 'product-tent-four-auto',
    details: ['Automatic frame.', 'Two entrances.', 'Includes storage bag and stakes.'],
    attributes: [['Capacity', '4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-emergency',
    category: 'tent',
    title: 'Compact Pop-Up Camping Tent for 2-4 People',
    subtitle: 'Compact weekend tent',
    price: 59,
    oldPrice: 79,
    discount: '25% OFF',
    installments: '4 payments of $14.75',
    image: productAssets.tents.cards[5],
    gallery: [productAssets.tents.cards[5], ...tentGallery.slice(1, 5)],
    rating: 4.3,
    reviews: 41,
    shipping: 'Free international shipping',
    available: 21,
    seller: 'Outdoor Express',
    color: 'Green',
    target: 'product-tent-emergency',
    details: ['Compact pop-up tent body.', 'Suitable for short camping trips.', 'Easy to fold and store.'],
    attributes: [['Capacity', '2 to 4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-transport',
    category: 'tent',
    title: 'Easy Transport Camping Tent with Ventilation Windows',
    subtitle: 'Portable camping option',
    price: 189,
    oldPrice: 249,
    discount: '24% OFF',
    installments: '4 payments of $47.25',
    image: productAssets.tents.cards[7],
    gallery: [productAssets.tents.cards[7], ...tentGallery.slice(2, 6)],
    rating: 4.8,
    reviews: 64,
    shipping: 'Free shipping',
    full: true,
    available: 11,
    seller: 'Trail Warehouse',
    color: 'Blue',
    target: 'product-tent-transport',
    details: ['Ventilation panels.', 'Packs into a carry case.', 'Designed for weekend trips.'],
    attributes: [['Capacity', '4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-foldable',
    category: 'tent',
    title: 'Foldable Camping Tent with Storage Bag, Easy Install',
    subtitle: 'Foldable tent kit',
    price: 99,
    oldPrice: 139,
    discount: '29% OFF',
    installments: '4 payments of $24.75',
    image: productAssets.tents.cards[8],
    gallery: [productAssets.tents.cards[8], ...tentGallery.slice(0, 4)],
    rating: 4.5,
    reviews: 76,
    shipping: 'Arrives free tomorrow',
    full: true,
    available: 15,
    seller: 'Camp Kit',
    color: 'Green',
    target: 'product-tent-foldable',
    details: ['Foldable structure.', 'Carry bag included.', 'Water-resistant outer shell.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-storage',
    category: 'tent',
    title: 'Waterproof Trail Tent with Stakes and Guy Ropes',
    subtitle: 'Complete trail tent setup',
    price: 24,
    oldPrice: 39,
    discount: '38% OFF',
    installments: '2 payments of $12',
    image: productAssets.tents.cards[1],
    gallery: [productAssets.tents.cards[1], ...tentGallery.slice(3, 7)],
    rating: 4.2,
    reviews: 29,
    shipping: 'Free shipping',
    available: 44,
    seller: 'Trail Kit',
    color: 'Forest green',
    target: 'product-tent-storage',
    details: ['Enclosed trail tent with waterproof floor.', 'Includes stakes and guy ropes.', 'Compact packed size for weekend trips.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-dome-family',
    category: 'tent',
    title: 'Family Dome Tent with Rain Cover for 4 People',
    subtitle: 'Balanced family option',
    price: 129,
    oldPrice: 179,
    discount: '28% OFF',
    installments: '4 payments of $32.25',
    image: productAssets.tents.cards[0],
    gallery: [productAssets.tents.cards[0], ...tentGallery.slice(0, 4)],
    rating: 4.6,
    reviews: 132,
    shipping: 'Arrives free tomorrow',
    full: true,
    available: 18,
    seller: 'Dome Supply',
    color: 'Green',
    target: 'product-tent-dome-family',
    details: ['Dome structure for fast weekend setup.', 'Includes rain cover and carry bag.', 'Mesh windows improve airflow.'],
    attributes: [['Capacity', '4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-backpacking-green',
    category: 'tent',
    title: 'Compact Backpacking Tent for 2 People, Dark Green',
    subtitle: 'Low-weight trail tent',
    price: 89.95,
    oldPrice: 119.95,
    discount: '25% OFF',
    installments: '4 payments of $22.49',
    image: productAssets.tents.cards[3],
    gallery: [productAssets.tents.cards[3], ...tentGallery.slice(2, 6)],
    rating: 4.4,
    reviews: 97,
    shipping: 'Arrives tomorrow',
    full: true,
    promoted: true,
    available: 28,
    seller: 'North Route',
    color: 'Dark green',
    target: 'product-tent-backpacking-green',
    details: ['Compact packed size for trail bags.', 'Weather-resistant fly.', 'Good ventilation for warm nights.'],
    attributes: [['Capacity', '2 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-cabin-rainfly',
    category: 'tent',
    title: 'Large Cabin Camping Tent with Extended Rainfly',
    subtitle: 'Roomier campsite setup',
    price: 249,
    oldPrice: 329,
    discount: '24% OFF',
    installments: '4 payments of $62.25',
    image: productAssets.tents.cards[7],
    gallery: [productAssets.tents.cards[7], ...tentGallery.slice(1, 6)],
    rating: 4.8,
    reviews: 58,
    shipping: 'Free shipping',
    available: 9,
    seller: 'Trail Warehouse',
    color: 'Blue',
    target: 'product-tent-cabin-rainfly',
    details: ['Tall cabin profile.', 'Extended rainfly for weather coverage.', 'Side ventilation panels.'],
    attributes: [['Capacity', '5 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-instant-blue',
    category: 'tent',
    title: 'Instant Setup Blue Tent for 2 to 3 People',
    subtitle: 'Entry price quick setup',
    price: 54.95,
    oldPrice: 74.95,
    discount: '27% OFF',
    installments: '2 payments of $27.48',
    image: productAssets.tents.cards[6],
    gallery: [productAssets.tents.cards[6], ...tentGallery.slice(3, 7)],
    rating: 4.3,
    reviews: 44,
    shipping: 'Free shipping',
    available: 36,
    seller: 'Camp Basic',
    color: 'Blue',
    target: 'product-tent-instant-blue',
    details: ['Instant opening frame.', 'Compact carry case.', 'Best for short casual stays.'],
    attributes: [['Capacity', '2 to 3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-screen-room',
    category: 'tent',
    title: 'Mesh Vent Cabin Tent for 4 People',
    subtitle: 'Ventilated cabin tent',
    price: 179,
    oldPrice: 239,
    discount: '25% OFF',
    installments: '4 payments of $44.75',
    image: productAssets.tents.cards[5],
    gallery: [productAssets.tents.cards[5], ...tentGallery.slice(0, 5)],
    rating: 4.5,
    reviews: 62,
    shipping: 'Free international shipping',
    promoted: true,
    available: 12,
    seller: 'Outdoor Express',
    color: 'White',
    target: 'product-tent-screen-room',
    details: ['Mesh windows for airflow.', 'Roomy cabin tent footprint.', 'Includes storage bag and stakes.'],
    attributes: [['Capacity', '4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-compact-travel',
    category: 'tent',
    title: 'Compact Travel Tent Kit with Waterproof Floor',
    subtitle: 'Good value travel kit',
    price: 69,
    oldPrice: 99,
    discount: '30% OFF',
    installments: '4 payments of $17.25',
    image: productAssets.tents.cards[8],
    gallery: [productAssets.tents.cards[8], ...tentGallery.slice(1, 5)],
    rating: 4.5,
    reviews: 83,
    shipping: 'Arrives free tomorrow',
    full: true,
    available: 20,
    seller: 'Camp Kit',
    color: 'Green',
    target: 'product-tent-compact-travel',
    details: ['Water-resistant floor.', 'Compact bag for storage.', 'Fast pole setup.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-quick-shelter',
    category: 'tent',
    title: 'Quick Setup Tent with Double Door and Carry Case',
    subtitle: 'Double-door camping tent',
    price: 109,
    oldPrice: 149,
    discount: '27% OFF',
    installments: '4 payments of $27.25',
    image: productAssets.tents.cards[9],
    gallery: [productAssets.tents.cards[9], ...tentGallery.slice(2, 6)],
    rating: 4.7,
    reviews: 71,
    shipping: 'Free shipping',
    full: true,
    available: 14,
    seller: 'Travel Kit',
    color: 'Blue',
    target: 'product-tent-quick-shelter',
    details: ['Two-door access.', 'Carry case included.', 'Water-resistant outer shell.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-backpacking-orange',
    category: 'tent',
    title: 'Lightweight Backpacking Tent for 2 People',
    subtitle: 'Budget portable tent',
    price: 39,
    oldPrice: 59,
    discount: '34% OFF',
    installments: '2 payments of $19.50',
    image: productAssets.tents.cards[4],
    gallery: [productAssets.tents.cards[4], ...tentGallery.slice(3, 7)],
    rating: 4.2,
    reviews: 37,
    shipping: 'Free shipping',
    available: 31,
    seller: 'Trail Light',
    color: 'Slate',
    target: 'product-tent-backpacking-orange',
    details: ['Light shell for casual trips.', 'Simple pole assembly.', 'Small packed size.'],
    attributes: [['Capacity', '2 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-park-family',
    category: 'tent',
    title: 'Family Park Tent with Awning and Ventilation Panels',
    subtitle: 'Spacious family tent',
    price: 159,
    oldPrice: 219,
    discount: '27% OFF',
    installments: '4 payments of $39.75',
    image: productAssets.tents.cards[2],
    gallery: [productAssets.tents.cards[2], ...tentGallery.slice(0, 5)],
    rating: 4.6,
    reviews: 111,
    shipping: 'Free shipping',
    full: true,
    available: 13,
    seller: 'Lawuto Outdoor',
    color: 'Beige',
    target: 'product-tent-park-family',
    details: ['Awning-style entry.', 'Ventilation panels on both sides.', 'Includes stakes and carry bag.'],
    attributes: [['Capacity', '4 people'], ['Condition', 'New']],
  },
  {
    id: 'tent-stake-shelter',
    category: 'tent',
    title: 'Waterproof Shelter Tent with Stakes and Guy Ropes',
    subtitle: 'Complete setup bundle',
    price: 74.95,
    oldPrice: 104.95,
    discount: '29% OFF',
    installments: '4 payments of $18.74',
    image: productAssets.tents.cards[1],
    gallery: [productAssets.tents.cards[1], ...tentGallery.slice(2, 6)],
    rating: 4.4,
    reviews: 69,
    shipping: 'Free international shipping',
    available: 25,
    seller: 'Camp Accessories',
    color: 'Blue',
    target: 'product-tent-stake-shelter',
    details: ['Bundle includes stakes and ropes.', 'Waterproof floor layer.', 'Easy storage after use.'],
    attributes: [['Capacity', '3 people'], ['Condition', 'New']],
  },
  {
    id: 'shoe-primary',
    category: 'shoe',
    title: 'Waterproof Trail Hiking Boots',
    subtitle: 'Recommended boot for wet trails',
    price: 129,
    oldPrice: 149,
    discount: '13% OFF',
    installments: '4 payments of $32.25',
    image: generatedShoeHero,
    gallery: [generatedShoeHero, ...shoeGallery],
    rating: 4.7,
    reviews: 391,
    shipping: 'Free international shipping',
    full: false,
    promoted: false,
    available: 23,
    seller: 'Supply Co. Trail',
    color: 'Black',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-primary',
    details: [
      'Waterproof upper helps keep feet dry on muddy routes.',
      'Lugged outsole adds grip on uneven trails.',
      'Padded collar and reinforced toe for hiking comfort.',
      'Choose size before adding to cart.',
    ],
    attributes: [
      ['Fit', 'Standard'],
      ['Recommended use', 'Hiking and trail walking'],
      ['Color', 'Black'],
      ['Condition', 'New'],
    ],
  },
  {
    id: 'shoe-sport',
    category: 'shoe',
    title: 'Lightweight Waterproof Hiking Boots',
    subtitle: 'Lightweight trail boot',
    price: 74.95,
    oldPrice: 99.95,
    discount: '25% OFF',
    installments: '4 payments of $18.74',
    image: productAssets.shoes.cards[1],
    gallery: [productAssets.shoes.cards[1], ...shoeGallery.slice(1, 5)],
    rating: 4.5,
    reviews: 128,
    shipping: 'Free shipping',
    full: true,
    available: 18,
    seller: 'Ridge & Rain',
    color: 'Charcoal',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-lightweight-waterproof',
    details: ['Waterproof textile upper.', 'Cushioned midsole.', 'Good for light trail use.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-tactical',
    category: 'shoe',
    title: 'Light Alpine Hiking Boots',
    subtitle: 'Durable ankle support',
    price: 89,
    oldPrice: 119,
    discount: '25% OFF',
    installments: '4 payments of $22.25',
    image: productAssets.shoes.cards[2],
    gallery: [productAssets.shoes.cards[2], ...shoeGallery.slice(0, 4)],
    rating: 4.6,
    reviews: 94,
    shipping: 'Free shipping',
    available: 14,
    seller: 'North Steps',
    color: 'Brown',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-tactical',
    details: ['High collar.', 'Reinforced sole.', 'Lightweight waterproof upper.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-gtx',
    category: 'shoe',
    title: 'Alpine Mid Waterproof Hiking Boots',
    subtitle: 'Premium mountain boot',
    price: 219,
    oldPrice: 279,
    discount: '22% OFF',
    installments: '4 payments of $54.75',
    image: productAssets.shoes.cards[3],
    gallery: [productAssets.shoes.cards[3], ...shoeGallery.slice(2, 6)],
    rating: 4.9,
    reviews: 73,
    shipping: 'Free shipping',
    full: true,
    available: 6,
    seller: 'Mountain Pro',
    color: 'Black',
    sizes: ['US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-gtx',
    details: ['Mid-cut hiking boot.', 'Waterproof membrane.', 'Advanced mountain outsole.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-comfort',
    category: 'shoe',
    title: 'Waterproof Mountain Hiking Comfort Boots',
    subtitle: 'Comfort fit trail boot',
    price: 69,
    oldPrice: 94,
    discount: '27% OFF',
    installments: '4 payments of $17.25',
    image: productAssets.shoes.cards[9],
    gallery: [productAssets.shoes.cards[9], ...shoeGallery.slice(1, 5)],
    rating: 4.4,
    reviews: 121,
    shipping: 'Free shipping',
    available: 20,
    seller: 'Trail Comfort',
    color: 'Black',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10'],
    target: 'product-shoe-comfort',
    details: ['Soft insole.', 'Water-resistant upper.', 'All-terrain traction.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-casual-gray',
    category: 'shoe',
    title: 'Black and Gray Waterproof Hiking Boots',
    subtitle: 'Comfort trail boot',
    price: 39,
    oldPrice: 59,
    discount: '34% OFF',
    installments: '2 payments of $19.50',
    image: productAssets.shoes.cards[4],
    gallery: [productAssets.shoes.cards[4], ...shoeGallery.slice(0, 4)],
    rating: 4.6,
    reviews: 58,
    shipping: 'Arrives tomorrow',
    full: true,
    promoted: true,
    available: 37,
    seller: 'Ridge & Rain',
    color: 'Gray',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-casual-gray',
    details: ['Waterproof outdoor profile.', 'Textured outsole.', 'Good value trail option.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-combat-light',
    category: 'shoe',
    title: 'Light Brown Hiking Boots with Ankle Support',
    subtitle: 'Supportive outdoor boot',
    price: 84,
    oldPrice: 109,
    discount: '23% OFF',
    installments: '4 payments of $21',
    image: productAssets.shoes.cards[5],
    gallery: [productAssets.shoes.cards[5], ...shoeGallery.slice(2, 6)],
    rating: 4.5,
    reviews: 81,
    shipping: 'Free international shipping',
    available: 16,
    seller: 'Cedar Ridge',
    color: 'Brown',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-combat-light',
    details: ['Light trail shape.', 'High traction sole.', 'Padded ankle support.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-waterproof-light',
    category: 'shoe',
    title: 'Lightweight Waterproof Hiking Boots',
    subtitle: 'Waterproof trail boot',
    price: 119,
    oldPrice: 139,
    discount: '14% OFF',
    installments: '4 payments of $29.75',
    image: productAssets.shoes.cards[6],
    gallery: [productAssets.shoes.cards[6], ...shoeGallery.slice(1, 5)],
    rating: 4.8,
    reviews: 103,
    shipping: 'Free shipping',
    full: true,
    available: 12,
    seller: 'North Route',
    color: 'Black',
    sizes: ['US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-waterproof-light',
    details: ['Waterproof upper.', 'Lightweight sole.', 'Reinforced toe and heel.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-hitec',
    category: 'shoe',
    title: 'Geo Sand All-Terrain Hiking Boots',
    subtitle: 'All-terrain boot',
    price: 129,
    oldPrice: 159,
    discount: '19% OFF',
    installments: '4 payments of $32.25',
    image: productAssets.shoes.cards[7],
    gallery: [productAssets.shoes.cards[7], ...shoeGallery.slice(0, 4)],
    rating: 4.7,
    reviews: 66,
    shipping: 'Free shipping',
    full: true,
    available: 7,
    seller: 'Summit Line',
    color: 'Brown',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-hitec',
    details: ['Mid trail profile.', 'All-terrain outsole.', 'Comfort collar.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-lightweight',
    category: 'shoe',
    title: 'Lightweight Waterproof Hiking Boots with Cushioned Sole',
    subtitle: 'Cushioned hiking boot',
    price: 99,
    oldPrice: 129,
    discount: '23% OFF',
    installments: '4 payments of $24.75',
    image: productAssets.shoes.cards[8],
    gallery: [productAssets.shoes.cards[8], ...shoeGallery.slice(2, 6)],
    rating: 4.6,
    reviews: 89,
    shipping: 'Free shipping',
    available: 24,
    seller: 'Trail Comfort',
    color: 'Black',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-lightweight',
    details: ['Cushioned sole.', 'Light boot construction.', 'Water-resistant trail upper.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-trail-brown',
    category: 'shoe',
    title: 'Brown Waterproof Trail Boots with Padded Ankle',
    subtitle: 'Brown ankle-support boot',
    price: 92,
    oldPrice: 119,
    discount: '23% OFF',
    installments: '4 payments of $23',
    image: productAssets.shoes.cards[4],
    gallery: [productAssets.shoes.cards[4], ...shoeGallery.slice(0, 4)],
    rating: 4.6,
    reviews: 77,
    shipping: 'Free shipping',
    full: true,
    available: 17,
    seller: 'North Steps',
    color: 'Brown',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-trail-brown',
    details: ['Padded ankle collar.', 'Water-resistant upper.', 'Grippy trail outsole.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-air-gray',
    category: 'shoe',
    title: 'Gray Waterproof Hiking Boots',
    subtitle: 'Lightweight waterproof boot',
    price: 49,
    oldPrice: 79,
    discount: '38% OFF',
    installments: '2 payments of $24.50',
    image: productAssets.shoes.cards[0],
    gallery: [productAssets.shoes.cards[0], ...shoeGallery.slice(1, 5)],
    rating: 4.4,
    reviews: 156,
    shipping: 'Arrives tomorrow',
    promoted: true,
    available: 42,
    seller: 'Ridge & Rain',
    color: 'Gray',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-air-gray',
    details: ['Lightweight waterproof profile.', 'Padded ankle collar.', 'Flexible outsole for day walks.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-nortiv-black',
    category: 'shoe',
    title: 'Black Mid Waterproof Hiking Boots',
    subtitle: 'Mid-cut waterproof boot',
    price: 99,
    oldPrice: 113,
    discount: '13% OFF',
    installments: '4 payments of $24.75',
    image: productAssets.shoes.cards[2],
    gallery: [productAssets.shoes.cards[2], ...shoeGallery.slice(2, 6)],
    rating: 4.7,
    reviews: 118,
    shipping: 'Arrives free tomorrow',
    full: true,
    available: 19,
    seller: 'North Route',
    color: 'Black',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-nortiv-black',
    details: ['Mid-cut support.', 'Waterproof outer material.', 'Reinforced heel for trail stability.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-xultra-gray',
    category: 'shoe',
    title: 'Ultra Mid Waterproof Mountain Boots, Gray',
    subtitle: 'Premium mountain profile',
    price: 249,
    installments: '4 payments of $62.25',
    image: productAssets.shoes.cards[3],
    gallery: [productAssets.shoes.cards[3], ...shoeGallery.slice(0, 5)],
    rating: 4.8,
    reviews: 49,
    shipping: 'Free shipping',
    full: true,
    available: 5,
    seller: 'Mountain Pro',
    color: 'Gray',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-xultra-gray',
    details: ['Mountain-grade grip.', 'Waterproof membrane.', 'Supportive mid collar.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-desert-sand',
    category: 'shoe',
    title: 'Sand Trail All-Terrain Hiking Boots',
    subtitle: 'All-terrain beige boot',
    price: 119,
    oldPrice: 149,
    discount: '20% OFF',
    installments: '4 payments of $29.75',
    image: productAssets.shoes.cards[7],
    gallery: [productAssets.shoes.cards[7], ...shoeGallery.slice(1, 5)],
    rating: 4.5,
    reviews: 64,
    shipping: 'Free international shipping',
    available: 11,
    seller: 'Summit Line',
    color: 'Beige',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-desert-sand',
    details: ['All-terrain outsole.', 'Comfort collar.', 'Neutral color for outdoor kits.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-carbon-mid',
    category: 'shoe',
    title: 'Carbon Mid Trekking Boots with Reinforced Toe',
    subtitle: 'Reinforced mid boot',
    price: 139,
    oldPrice: 179,
    discount: '21% OFF',
    installments: '4 payments of $34.75',
    image: productAssets.shoes.cards[6],
    gallery: [productAssets.shoes.cards[6], ...shoeGallery.slice(2, 6)],
    rating: 4.7,
    reviews: 86,
    shipping: 'Free shipping',
    full: true,
    available: 15,
    seller: 'North Route',
    color: 'Black',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-carbon-mid',
    details: ['Reinforced toe cap.', 'Waterproof light shell.', 'Stable outsole for wet terrain.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-red-trail',
    category: 'shoe',
    title: 'Red Accent Waterproof Hiking Boots with Grip Sole',
    subtitle: 'Trail boot with red accents',
    price: 69,
    oldPrice: 94,
    discount: '27% OFF',
    installments: '4 payments of $17.25',
    image: productAssets.shoes.cards[9],
    gallery: [productAssets.shoes.cards[9], ...shoeGallery.slice(0, 4)],
    rating: 4.4,
    reviews: 105,
    shipping: 'Free shipping',
    available: 22,
    seller: 'Trail Comfort',
    color: 'Black',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-red-trail',
    details: ['Water-resistant trail upper.', 'Grip outsole.', 'Cushioned insole for longer walks.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-low-hiker',
    category: 'shoe',
    title: 'Lightweight Trail Hiking Boots with Rugged Sole',
    subtitle: 'Flexible hiking boot',
    price: 59,
    oldPrice: 79,
    discount: '25% OFF',
    installments: '4 payments of $14.75',
    image: productAssets.shoes.cards[1],
    gallery: [productAssets.shoes.cards[1], ...shoeGallery.slice(1, 5)],
    rating: 4.3,
    reviews: 91,
    shipping: 'Arrives tomorrow',
    full: true,
    promoted: true,
    available: 33,
    seller: 'Ridge & Rain',
    color: 'Gray',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10'],
    target: 'product-shoe-low-hiker',
    details: ['Light boot silhouette.', 'Rugged outdoor tread.', 'Light cushioning for day routes.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-rugged-black',
    category: 'shoe',
    title: 'Rugged Black Outdoor Boots with High Traction Sole',
    subtitle: 'Durable black boot',
    price: 89,
    oldPrice: 119,
    discount: '25% OFF',
    installments: '4 payments of $22.25',
    image: productAssets.shoes.cards[8],
    gallery: [productAssets.shoes.cards[8], ...shoeGallery.slice(2, 6)],
    rating: 4.5,
    reviews: 72,
    shipping: 'Free shipping',
    available: 18,
    seller: 'Trail Comfort',
    color: 'Black',
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    target: 'product-shoe-rugged-black',
    details: ['High-traction sole.', 'Durable outdoor upper.', 'Cushioned collar.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
  {
    id: 'shoe-allweather-brown',
    category: 'shoe',
    title: 'All-Weather Brown Hiking Boots with Lugged Sole',
    subtitle: 'Weather-ready trail boot',
    price: 109,
    oldPrice: 139,
    discount: '22% OFF',
    installments: '4 payments of $27.25',
    image: productAssets.shoes.cards[5],
    gallery: [productAssets.shoes.cards[5], ...shoeGallery.slice(0, 4)],
    rating: 4.6,
    reviews: 84,
    shipping: 'Free international shipping',
    available: 16,
    seller: 'Cedar Ridge',
    color: 'Brown',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
    target: 'product-shoe-allweather-brown',
    details: ['Weather-ready synthetic upper.', 'Lugged outsole.', 'Stable ankle shape.'],
    attributes: [['Fit', 'Standard'], ['Condition', 'New']],
  },
];

function scaleMoney(value: number) {
  return Math.round((value * PRODUCT_PRICE_MULTIPLIER + Number.EPSILON) * 100) / 100;
}

function formatScaledInstallment(value: number) {
  const scaled = scaleMoney(value);
  return Number.isInteger(scaled) ? String(scaled) : scaled.toFixed(2);
}

function scaleInstallments(copy: string) {
  return copy.replace(/\$(\d+(?:\.\d+)?)/g, (_, amount: string) => {
    return '$' + formatScaledInstallment(Number(amount));
  });
}

function scaleProductPrice(product: Product): Product {
  return {
    ...product,
    price: scaleMoney(product.price),
    oldPrice: product.oldPrice === undefined ? undefined : scaleMoney(product.oldPrice),
    installments: scaleInstallments(product.installments),
  };
}

export const products: Product[] = baseProducts.map(scaleProductPrice);

export const searchCopy = {
  tent: {
    query: 'camping tent',
    heading: 'Camping tents',
    breadcrumb: 'Sports & Fitness > Camping > Tents',
    count: '9,999+ results',
    related: ['4 person tent', 'automatic tent', 'camping house', 'waterproof tent'],
  },
  shoe: {
    query: 'hiking boots',
    heading: 'Hiking boots',
    breadcrumb: 'Outdoor > Footwear > Hiking Boots',
    count: '6,088 results',
    related: ['waterproof boots', 'trail shoes', 'mountain boots', 'wet trail footwear'],
  },
} satisfies Record<Category, {
  query: string;
  heading: string;
  breadcrumb: string;
  count: string;
  related: string[];
}>;
